const fs = require('fs');
const path = require('path');

const contextPath = path.join(__dirname, 'context/LanguageContext.tsx');
let content = fs.readFileSync(contextPath, 'utf8');

const additions = {
  en: {
    dashboardTitle: 'Security Dashboard',
    dashboardDesc: 'Real-time enterprise-grade IAM monitoring',
    systemLive: 'System Live',
    totalEmployees: 'Total Employees',
    registeredUsers: 'Registered users',
    activeSessions: 'Active Sessions',
    last24Hours: 'Last 24 hours',
    securityAlerts: 'Security Alerts',
    requiringReview: 'Requiring review',
    systemRisk: 'System Risk',
    automatedEval: 'Automated evaluation',
    realtimeStream: 'Real-time Authentication Stream',
    showingLast20: 'Showing last 20 events',
    noAuthEvents: 'No authentication events yet. Events will appear here in real-time.',
    event: 'Event',
    user: 'User',
    source: 'Source',
    status: 'Status',
    time: 'Time',
    authorizedSession: 'Authorized Session',
    blockedAttempt: 'Blocked Attempt',
    success: 'Success',
    failed: 'Failed',
    unknown: 'Unknown'
  },
  hi: {
    dashboardTitle: 'सुरक्षा डैशबोर्ड',
    dashboardDesc: 'वास्तविक समय में उद्यम-स्तरीय IAM निगरानी',
    systemLive: 'सिस्टम लाइव है',
    totalEmployees: 'कुल कर्मचारी',
    registeredUsers: 'पंजीकृत उपयोगकर्ता',
    activeSessions: 'सक्रिय सत्र',
    last24Hours: 'पिछले 24 घंटे',
    securityAlerts: 'सुरक्षा अलर्ट',
    requiringReview: 'समीक्षा की आवश्यकता है',
    systemRisk: 'सिस्टम जोखिम',
    automatedEval: 'स्वचालित मूल्यांकन',
    realtimeStream: 'रियल-टाइम ऑथेंटिकेशन स्ट्रीम',
    showingLast20: 'अंतिम 20 ईवेंट दिखा रहा है',
    noAuthEvents: 'अभी तक कोई प्रमाणीकरण ईवेंट नहीं है। ईवेंट वास्तविक समय में यहां दिखाई देंगे।',
    event: 'ईवेंट',
    user: 'उपयोगकर्ता',
    source: 'स्रोत',
    status: 'स्थिति',
    time: 'समय',
    authorizedSession: 'अधिकृत सत्र',
    blockedAttempt: 'अवरुद्ध प्रयास',
    success: 'सफल',
    failed: 'विफल',
    unknown: 'अज्ञात'
  },
  es: {
    dashboardTitle: 'Panel de Seguridad',
    dashboardDesc: 'Monitoreo de IAM de nivel empresarial en tiempo real',
    systemLive: 'Sistema en Vivo',
    totalEmployees: 'Total de Empleados',
    registeredUsers: 'Usuarios registrados',
    activeSessions: 'Sesiones Activas',
    last24Hours: 'Últimas 24 horas',
    securityAlerts: 'Alertas de Seguridad',
    requiringReview: 'Requiere revisión',
    systemRisk: 'Riesgo del Sistema',
    automatedEval: 'Evaluación automatizada',
    realtimeStream: 'Flujo de Autenticación en Tiempo Real',
    showingLast20: 'Mostrando los últimos 20 eventos',
    noAuthEvents: 'Aún no hay eventos de autenticación. Los eventos aparecerán aquí en tiempo real.',
    event: 'Evento',
    user: 'Usuario',
    source: 'Fuente',
    status: 'Estado',
    time: 'Tiempo',
    authorizedSession: 'Sesión Autorizada',
    blockedAttempt: 'Intento Bloqueado',
    success: 'Éxito',
    failed: 'Fallido',
    unknown: 'Desconocido'
  },
  fr: {
    dashboardTitle: 'Tableau de Bord de Sécurité',
    dashboardDesc: 'Surveillance IAM d\'entreprise en temps réel',
    systemLive: 'Système en Direct',
    totalEmployees: 'Total des Employés',
    registeredUsers: 'Utilisateurs enregistrés',
    activeSessions: 'Sessions Actives',
    last24Hours: 'Dernières 24 heures',
    securityAlerts: 'Alertes de Sécurité',
    requiringReview: 'Nécessite une révision',
    systemRisk: 'Risque Système',
    automatedEval: 'Évaluation automatisée',
    realtimeStream: 'Flux d\'Authentification en Temps Réel',
    showingLast20: 'Affichage des 20 derniers événements',
    noAuthEvents: 'Aucun événement d\'authentification pour l\'instant. Les événements apparaîtront ici en temps réel.',
    event: 'Événement',
    user: 'Utilisateur',
    source: 'Source',
    status: 'Statut',
    time: 'Temps',
    authorizedSession: 'Session Autorisée',
    blockedAttempt: 'Tentative Bloquée',
    success: 'Succès',
    failed: 'Échoué',
    unknown: 'Inconnu'
  },
  de: {
    dashboardTitle: 'Sicherheits-Dashboard',
    dashboardDesc: 'Echtzeit-IAM-Überwachung auf Unternehmensebene',
    systemLive: 'System Live',
    totalEmployees: 'Mitarbeiter Gesamt',
    registeredUsers: 'Registrierte Benutzer',
    activeSessions: 'Aktive Sitzungen',
    last24Hours: 'Letzte 24 Stunden',
    securityAlerts: 'Sicherheitswarnungen',
    requiringReview: 'Überprüfung erforderlich',
    systemRisk: 'Systemrisiko',
    automatedEval: 'Automatisierte Auswertung',
    realtimeStream: 'Echtzeit-Authentifizierungs-Stream',
    showingLast20: 'Zeige die letzten 20 Ereignisse',
    noAuthEvents: 'Noch keine Authentifizierungsereignisse. Ereignisse werden hier in Echtzeit angezeigt.',
    event: 'Ereignis',
    user: 'Benutzer',
    source: 'Quelle',
    status: 'Status',
    time: 'Zeit',
    authorizedSession: 'Autorisierte Sitzung',
    blockedAttempt: 'Blockierter Versuch',
    success: 'Erfolg',
    failed: 'Fehlgeschlagen',
    unknown: 'Unbekannt'
  },
  ta: {
    dashboardTitle: 'பாதுகாப்பு டாஷ்போர்டு',
    dashboardDesc: 'நிகழ்நேர நிறுவன-நிலை IAM கண்காணிப்பு',
    systemLive: 'கணினி இயங்குகிறது',
    totalEmployees: 'மொத்த ஊழியர்கள்',
    registeredUsers: 'பதிவுசெய்யப்பட்ட பயனர்கள்',
    activeSessions: 'செயலில் உள்ள அமர்வுகள்',
    last24Hours: 'கடந்த 24 மணிநேரம்',
    securityAlerts: 'பாதுகாப்பு எச்சரிக்கைகள்',
    requiringReview: 'மதிப்பாய்வு தேவை',
    systemRisk: 'கணினி ஆபத்து',
    automatedEval: 'தானியங்கி மதிப்பீடு',
    realtimeStream: 'நிகழ்நேர அங்கீகார ஸ்ட்ரீம்',
    showingLast20: 'கடைசி 20 நிகழ்வுகளைக் காட்டுகிறது',
    noAuthEvents: 'அங்கீகார நிகழ்வுகள் எதுவும் இல்லை. நிகழ்வுகள் நிகழ்நேரத்தில் இங்கே தோன்றும்.',
    event: 'நிகழ்வு',
    user: 'பயனர்',
    source: 'மூலம்',
    status: 'நிலை',
    time: 'நேரம்',
    authorizedSession: 'அங்கீகரிக்கப்பட்ட அமர்வு',
    blockedAttempt: 'தடுக்கப்பட்ட முயற்சி',
    success: 'வெற்றி',
    failed: 'தோல்வி',
    unknown: 'தெரியவில்லை'
  }
};

for (const [lang, keys] of Object.entries(additions)) {
  const replacementString = Object.entries(keys)
    .map(([k, v]) => `    ${k}: '${v.replace(/'/g, "\\'")}',`)
    .join('\n');
  
  const regex = new RegExp(`(${lang}: \\{[\\s\\S]*?)(  \\},)`, 'g');
  content = content.replace(regex, `$1${replacementString}\n$2`);
}

fs.writeFileSync(contextPath, content, 'utf8');
console.log('Language context updated successfully.');
